create a new navigation menu
InfinityLabsCode/secure-voting-app pull request #4
Opened 2022-12-12 09:11 UTC by Nahid01920

2022-12-12 11:09 UTC, InfinityLabsCode requested changes
Add prettier in your vs code and format the code

2022-12-15 06:00 UTC, InfinityLabsCode commented on styles/globals.scss
> +.login-area {
Why using css files instead of tailwind?

2022-12-15 06:00 UTC, InfinityLabsCode commented on pages/createpoll.tsx
> +      <Fotter />
Footer spelling is wrong.

2022-12-15 06:06 UTC, Nahid01920 commented on pages/createpoll.tsx
> +      <Fotter />
fixed

2022-12-25 05:07 UTC, InfinityLabsCode approved these changes

2022-12-25 05:07 UTC, merged